file.remove("iot_server.lua")
file.open("iot_server.lua","w")
file.write([[srv=net.createServer(net.TCP)]])
file.write([[srv:listen(80,function(conn)]])
file.write([[    conn:on("receive", function(client,request)]])
file.write([[        local buf = "";]])
file.write([[        local _, _, method, path, vars = string.find(request, "([A-Z]+) (.+)?(.+) HTTP");]])
file.write([[        if(method == nil)then]])
file.write([[            _, _, method, path = string.find(request, "([A-Z]+) (.+) HTTP");]])
file.write([[        end]])
file.write([[        local _GET = {}]])
file.write([[        if (vars ~= nil)then]])
file.write([[            for k, v in string.gmatch(vars, "(%w+)=(%w+)&*") do]])
file.write([[                _GET[k] = v]])
file.write([[            end]])
file.write([[        end]])
file.write([[        buf = buf.."<h1> ESP8266 Web Server</h1>";]])
file.write([[        buf = buf.."<p>Vermelho <a href=\"?pin=ON1\"><button>ON</button></a>&nbsp;<a href=\"?pin=OFF1\"><button>OFF</button></a></p>";]])
file.write([[        buf = buf.."<p>Verde <a href=\"?pin=ON2\"><button>ON</button></a>&nbsp;<a href=\"?pin=OFF2\"><button>OFF</button></a></p>";]])
file.write([[        buf = buf.."<p>Azul <a href=\"?pin=ON3\"><button>ON</button></a>&nbsp;<a href=\"?pin=OFF3\"><button>OFF</button></a></p>";]])
file.write([[        buf = buf.."<br><br>";]])
file.write([[        buf = buf.."<h2>Pedro Minatel</h2>";]])
file.write([[        local _on,_off = "",""]])
file.write([[        if(_GET.pin == "ON1")then]])
file.write([[              print("ON1")]])
file.write([[        elseif(_GET.pin == "OFF1")then]])
file.write([[              print("OFF1")]])
file.write([[        elseif(_GET.pin == "ON2")then]])
file.write([[              print("ON2")]])
file.write([[        elseif(_GET.pin == "OFF2")then]])
file.write([[              print("OFF2")]])
file.write([[        elseif(_GET.pin == "ON3")then]])
file.write([[              print("ON3")]])
file.write([[        elseif(_GET.pin == "OFF3")then]])
file.write([[              print("OFF3")]])
file.write([[        end]])
file.write([[        client:send(buf);]])
file.write([[        client:close();]])
file.write([[        collectgarbage();]])
file.write([[    end)]])
file.write([[end)]])
file.close()
file.open("init.lua","w")
file.write([[dofile("iot_server.lua")]])
file.close()